"""QuerySpec 的定义与校验、默认值表、确认卡文案的生成。零内部依赖。

其他模块只从这里 import（ARCHITECTURE §1.2 第 3 条）。
"""

from litmus.spec.confirm import (
    AFTER,
    EVENT,
    HOW,
    WHAT,
    WHEN,
    WHO,
    Assumption,
    Confirm,
    Facts,
    Mention,
    group_order,
    render_confirm,
    small_cap_note,
    summarize,
)
from litmus.spec.defaults import (
    BENCHMARKS,
    DEFAULTS,
    MAX_COST_BPS,
    MAX_HORIZON,
    MAX_HORIZONS,
    MAX_LIMIT,
)
from litmus.spec.query import (
    TARGETS,
    BoardRef,
    CardOutput,
    Condition,
    DateRange,
    Event,
    EventStudyOutput,
    Metric,
    QuerySpec,
    Scope,
    Sort,
    Subject,
    TableOutput,
    When,
    parse_spec,
)

__all__ = [
    "AFTER",
    "BENCHMARKS",
    "DEFAULTS",
    "EVENT",
    "HOW",
    "MAX_COST_BPS",
    "MAX_HORIZON",
    "MAX_HORIZONS",
    "MAX_LIMIT",
    "TARGETS",
    "WHAT",
    "WHEN",
    "WHO",
    "Assumption",
    "BoardRef",
    "CardOutput",
    "Condition",
    "Confirm",
    "DateRange",
    "Event",
    "EventStudyOutput",
    "Facts",
    "Mention",
    "Metric",
    "QuerySpec",
    "Scope",
    "Sort",
    "Subject",
    "TableOutput",
    "When",
    "group_order",
    "parse_spec",
    "render_confirm",
    "small_cap_note",
    "summarize",
]
